import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";
import { ReduxProvider } from "@/store/ReduxProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Toaster />
          <Navbar />
          <ReduxProvider>{children}</ReduxProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
