import type { Metadata } from "next";
import ShaderWrapper from "@/components/BG/RippleWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ShaderWrapper visible={true} />
      {children}
    </>
  );
}
